language: node_js
node_js:
- '5'
services:
- redis
addons:
  code_climate:
    repo_token: 114f66f5afda0bbd4467329fbeeff7a9255e9c4c0c482269e5634c33fb73d3e3
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  - CXX=g++-4.8
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
after_success:
- bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - "/^v[0-9]/"
